name: Download Request
description: Submit magnet links for automated download
title: "[Download]: "
labels: ["download-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Torrent Download Request
        Submit one or more magnet links to download and create a GitHub release.
        **Enter one magnet link per line.**
        
  - type: textarea
    id: magnet_links
    attributes:
      label: Magnet Links
      description: Paste magnet links here (one per line)
      placeholder: |
        magnet:?xt=urn:btih:...
        magnet:?xt=urn:btih:...
      render: text
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Release Description (Optional)
      description: Optional description for the release
      placeholder: "Downloaded from..."
    validations:
      required: false
