name: Download Request
description: Submit a magnet link for automated download
title: "[Download]: "
labels: ["download-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Torrent Download Request
        Submit a magnet link to download and create a GitHub release.
        
  - type: input
    id: magnet_link
    attributes:
      label: Magnet Link
      description: Paste the complete magnet link here
      placeholder: "magnet:?xt=urn:btih:..."
    validations:
      required: true
      
  - type: input
    id: release_name
    attributes:
      label: Release Name
      description: Name for the GitHub release (will be used as tag)
      placeholder: "v1.0.0 or my-download-1"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Release Description
      description: Optional description for the release
      placeholder: "Downloaded from..."
    validations:
      required: false
